TRAIN:
  ENABLE: True
  DATASET: stip
  BATCH_SIZE: 1
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
DATA:
  PATH_TO_DATA_DIR: /home/nico/TimeSformer
  NUM_FRAMES: 8
  NUM_CAMERAS: 2
  SAMPLING_RATE: 32
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
MODEL:
  MODEL_NAME: GeoFormer
  NUM_CLASSES: 400
  MLP_HIDDEN_DIM: 120
  MLP_NUM_HIDDEN_LAYERS: 2
  MLP_OUTPUT_DIM: 120
  ARCH: vit
  LOSS_FUNC: homography_loss
  DROPOUT_RATE: 0.5
TIMESFORMER:
  ATTENTION_TYPE: 'divided_space_time'
  PRETRAINED_MODEL: /home/nico/TimeSformer/TimeSformer_divST_8x32_224_K600.pyth
SOLVER:
  BASE_LR: 0.000000001
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 11, 14]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 15
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
TEST:
  ENABLE: True
  DATASET: stip
  BATCH_SIZE: 1
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
TENSORBOARD:
  ENABLE: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
